#!/bin/bash
set -e

mariadb -u root -p"${MYSQL_ROOT_PASSWORD}" -e "
CREATE DATABASE IF NOT EXISTS \`${WP_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${WP_DB_USER}'@'%' IDENTIFIED BY '${WP_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${WP_DB_NAME}\`.* TO '${WP_DB_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`${MOODLE_DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MOODLE_DB_USER}'@'%' IDENTIFIED BY '${MOODLE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MOODLE_DB_NAME}\`.* TO '${MOODLE_DB_USER}'@'%';

FLUSH PRIVILEGES;
"
